services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    restart: always
    ports: 
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - podrick

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: always
    ports:
      - "${ALLOY_PORT}:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - alloy_data:/var/lib/alloy/data
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    depends_on:
      - loki
    networks:
      - podrick

