services:
  mlflow_backend_postgres:
    image: postgres:14
    container_name: mlflow_backend_store_postgres
    restart: always
    environment:
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
    ports:
      - "6333:5432"
    volumes:
      - mlflow_postgres_volume:/var/lib/postgresql/data
    networks:
      - podrick
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MLFLOW_POSTGRES_USER} -d ${MLFLOW_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

